### ISSUE TITLE
.solid 子元素点击事件无效

### ISSUE THREAD

**Issue by metanoia1989** [weilanwl/ColorUI#10]
代码如下
**test.wxml**
```html
<view class="solid box">
  <button bindtap="clickConsole" class="btn primary">测试 solid </button>
</view>
```
**test.js**
```js
Page({
  clickConsole: function() {
    console.log('click!');
  }
})
```

css也能导致按钮的bindtap事件失效，发现把`.solid::after`的宽度高度设为100%就可以了，或者加上`pointer-events: none`
```css
.solid::after {
    position: absolute;
    top: 0;
    left: 0;
    width: 200%;
    height: 200%;
    content: " ";
    -webkit-transform: scale(.5);
    transform: scale(.5);
    -webkit-transform-origin: 0 0;
    transform-origin: 0 0;
    pointer-events: none
}
```
